### ISSUE TITLE
TypeError: ExtensionUtils.getSettings is not a function

### ISSUE THREAD

**Issue by xhamir** [iamlemec/miniview#14]
After update stop working for me. 

Ubuntu 18.04.3 LTS
GNOME Shell 3.28.3

Error:

TypeError: ExtensionUtils.getSettings is not a function

Stack trace:
  _init@/home/jair/.local/share/gnome-shell/extensions/miniview@thesecretaryofwar.com/prefs.js:19:26
  buildPrefsWidget@/home/jair/.local/share/gnome-shell/extensions/miniview@thesecretaryofwar.com/prefs.js:114:18
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43

**Comment by iamlemec** [comment]
Thanks for the report! Yep, this has an easy fix. Should have it committed and submitted tonight. Hopefully live on the website in a few days.

**Comment by iamlemec** [comment]
Hmm, interesting, I'm running Ubuntu 18.04 in a VM now and I'm getting a different error (related to the one raised in #13). What's your `gjs` version? Also, could you perhaps try out the latest version here on GitHub and let me know what it says? It might still not work, but would help me in figuring out exactly what's going on. Thanks!

**Comment by xhamir** [comment]
Sorry to not answer i didnt see the comments, but with the last update everything is working fine, thanks.
