### ISSUE TITLE
Shell 3.30 support

### ISSUE THREAD

**Issue by JoseLSegura** [iamlemec/miniview#2]
With the release of Gnome-Shell 3.30 this extension stopped working.

Do you have plans for releasing a new version for Shell 3.30?

Thanks in advance

**Comment by iamlemec** [comment]
Definitely. I don't have 3.30 installed yet, but will soon, and I can test it then.

In the meantime, any idea why it's not working? It just doesn't show up I guess? Any errors reported in looking glass?

**Comment by JoseLSegura** [comment]
In looking glass it shows this error:

`TypeError: global.screen is undefined`

When I remove it and just install it again, the mini view is shown. I can move it but I cannot hide, change which Window is shown...

After a Shell reboot, the miniview is not shown at all anymore

**Comment by JoseLSegura** [comment]
And of course, if you want I can test anything you ask me on my desktop. I'm running Debian Sid that already have Shell 3.30 installed

**Comment by iamlemec** [comment]
Yup, should be `global.screen` for `global.display`!

Just tested the older version (3.28), and it works fine. The current `master` here is the updated and working version. Submitting to extensions.gnome.org now.
