### ISSUE TITLE
Not Working in Gnome 3.36

### ISSUE THREAD

**Issue by dexmendonca** [iamlemec/miniview#21]
the miniview window does not move in Gnome 3.36 , and it doesn't resize either
Can you help me?
OS: Arch Linux
Gnome version: 3.36.0
Thank you

**Comment by AdsonCicilioti** [comment]
On Wayland or Xorg session?

**Comment by dexmendonca** [comment]
Xorg session

**Comment by iamlemec** [comment]
Another release, another set of fixes! I'm seeing the same there here. It shows up but it's not responsive. The menu is there and works. However, after startup (or restart), if you disable then reenable the extension through gnome tweaks, it works fine after that.

So in the short run, that's a workaround. I'm looking into figuring out why this is happening. I'm not seeing any errors in the logs. Anyone getting miniview related errors in logs?

**Comment by AdsonCicilioti** [comment]
Here:
OS: Arch Linux
Gnome version: 3.36.0

Works... But some times the miniview is not clicklabe/Draggrable/Resizeable. After Disable/re-enable returns works.

@iamlemec Very thanks for this extension. I no have knowledge to dev helps, but if help, get reference from Pip function of Elementary. But the miniview is on the right way.

**Comment by ewerton-silva00** [comment]
Hi, everyone.

I'm having trouble running the miniview.

```
Ubuntu 20.04 LTS
GNOME Shell 3.36.1
```

Below the errors I find in the logs.

```
mai 04 11:41:11 lenovo-b490 gnome-shell[3463]: JS ERROR: TypeError: _gsmPrefs is null
                                               _onPreferences@/home/ewerton/.local/share/gnome-shell/extensions/miniview@thesecretaryofwar.com/extension.js:108:13
                                               activate@resource:///org/gnome/shell/ui/popupMenu.js:191:14
                                               vfunc_button_release_event@resource:///org/gnome/shell/ui/popupMenu.js:138:14
```

**Comment by iamlemec** [comment]
Ok! Thanks for the feedback everyone. Finally figured this one out. Turns out `Clutter.Group` is semi-defunct and we should just use `Clutter.Actor` which behaves better with the shell. With the latest commit, it's working for me on 3.37. Would be great if you all could test it out on your machines @AdsonCicilioti and @dexmendonca! Note that if you are running directly from the github repo, you need to run `glib-compile-schemas .` in the `schemas` directory to update some of the preference specifications.

@ewerton-silva00 this is a slightly different issue where there is yet another way to bring up the preferences dialog, it should be fixed in the latest commit as well. Let me know if that works for you!

**Comment by dexmendonca** [comment]
Hello, the gnome extension version is not working yet.
Do you have any tutorial to install using github repo version?
Thanks

**Comment by Jeansen** [comment]
@dexmendonca just replace the folder in `~/share/gnome-shell/extensions/miniview@thesecretaryofwar.com` with the contents of this repo. Like this:

```
rm -f ~/share/gnome-shell/extensions/miniview@thesecretaryofwar.com
git clone https://github.com/iamlemec/miniview.git ~/share/gnome-shell/extensions/miniview@thesecretaryofwar.com
```

Then log out and back in again :)

**Comment by Jeansen** [comment]
@iamlemec Just cloned the master and tested it. Works the same as it did all the time for me when still using Gnome 3.34.

Doing  `glib-compile-schemas .` from within the schemas folder did not change anything. At least I can see no changes when I do `git status`.

Anyway, I can confirm it works (for me) :+1:

**Comment by iamlemec** [comment]
@Jeansen awesome! thanks. yeah, I forgot that the repo includes the compiled schema file, so that makes sense.

**Comment by Jeansen** [comment]
I found one thing that is different though with Gnome 3.36. When I awake my Laptop from Power-Saving mode and log back in, I cannot bring back Miniview with Shift-F12. LookingGlass unfortunately does not show anything, either. So, I cannot tell, if there's something in the logs.

**Comment by dexmendonca** [comment]
"It Works!" for me, Thanks @iamlemec
