### ISSUE TITLE
Not working on Gnome 41

### ISSUE THREAD

**Issue by dexmendonca** [iamlemec/miniview#27]
This extension doesn't work anymore.

**Comment by iamlemec** [comment]
Are you installing from the Gnome Extensions website or cloning the repo from here? The one on extensions isn't updated for Gnome 41 yet (but I'm doing that now). The one here should work for 41.

**Comment by iamlemec** [comment]
Ok, the version on Gnome Extensions should support 41. If it still doesn't work, let me know what errors you're seeing, hopefully I can help out!

**Comment by dexmendonca** [comment]
it works now! Thanks ! :D
