### ISSUE TITLE
Preferences page error

### ISSUE THREAD

**Issue by abhishekmj303** [iamlemec/miniview#28]
**OS** :  Ubuntu LTS 20.04
**GNOME Shell** : 3.36.9

Not able to change settings through gnome tweaks or extensions app. But the extension works fine.
![Screenshot from 2022-01-01 20-35-46](https://user-images.githubusercontent.com/85760664/147853594-43480008-2c78-41af-b550-5215dc3ac3a7.png)

The settings of extension miniview@thesecretaryofwar.com had an error:
```
TypeError: this._frame.set_child is not a function
```

Stack trace:
```
_init@/home/abhishek/.local/share/gnome-shell/extensions/miniview@thesecretaryofwar.com/prefs.js:100:21
buildPrefsWidget@/home/abhishek/.local/share/gnome-shell/extensions/miniview@thesecretaryofwar.com/prefs.js:144:18
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by iamlemec** [comment]
Yep, looks like the extension is expecting GTK4 but Gnome Shell 3.36 uses GTK3. Did you install via the Gnome Extensions site or by cloning from this repo? If from Gnome Extensions, try installing version 7 of the extension. If from this repo, check out the "pre-40" branch and it should work. Thanks and let me know how that goes!

**Comment by iamlemec** [comment]
Quick update: I tweaked some things on Gnome Extensions and it should work right out of the box for version 3.36 now.

**Comment by abhishekmj303** [comment]
@iamlemec Oh, my bad. Installed wrong version. It is now working flawlessly with default install also. Thank you :)
