### ISSUE TITLE
Miniview disappears upon entering Activities

### ISSUE THREAD

**Issue by pesader** [iamlemec/miniview#39]
Once you enter the Activities view, the miniview window disappears. However, it reappears as soon as you change workspace or leave the Activities view.

Here's a screencast to demonstrate the issue:

https://user-images.githubusercontent.com/65264536/223157830-a6ae25cf-d2a2-4c26-abd9-7a56e132ddab.mp4

**Comment by iamlemec** [comment]
okay, just pushed a fix here. it was showing on a notify::focus-window event, not sure why. but removing that handler works.

**Comment by pesader** [comment]
Cool, I'll build and install it from source code to help you test it out :)

**Comment by pesader** [comment]
I found an issue on commit 638e99f, that I was not able to reproduce on the commit that came before it.

Sometimes, when I close a window, Miniview seems to lose track of the window it should show. When that happens, the only way to recover is by selecting "Next Window" or "Previous Window" from the panel icon then toggling Miniview on and off (once). Here's a video of that happening:

https://user-images.githubusercontent.com/65264536/231926169-2967a407-9b2b-4cc9-8c24-e18de37e0051.mp4

**Comment by pesader** [comment]
In any case, I think the most desirable behavior would be always showing up on overview, not the contrary. I think the idea of having a picture-in-picture window is to have it constantly floating there, no matter the state of the desktop.

**Comment by iamlemec** [comment]
Thanks for the rapid testing! I'm convinced actually, we should just have it visible all the time. It always was a bit jarring how it disappeared during overview. Just pushed that change, along with a revert of iamlemec/miniview@638e99f. Let me know how that works!

**Comment by pesader** [comment]
Yep, I like it much better!


https://user-images.githubusercontent.com/65264536/232065670-b72a63ff-d90b-47d0-ac32-4ed73583211e.mp4

Thank you for addressing this so promptly :)
