### ISSUE TITLE
vertical alignment on panel

### ISSUE THREAD

**Issue by zagr0** [iamlemec/miniview#4]
Hi, there is issue when panel high is not default, the vertical position is not centered
![image](https://user-images.githubusercontent.com/19431669/50010847-2b99b780-ffc3-11e8-89dd-e82c0d3fd5da.png)

could you please fix that?

**Comment by iamlemec** [comment]
Thanks for the report! Yeah, I had just set the top padding to 4px so it fit on my particular setup. Obviously not robust. Just pushed a fix that vertically centers the text instead.

I don't want to overwhelm the extensions.gnome.org folks, so I'm going to incorporate a few more fixes I've been working on lately, then submit there in a few days.

**Comment by zagr0** [comment]
Thnx!

**Comment by lverissimo** [comment]
great... I had the same exact issue, and I played with it and changed extension.js with the following:
'''
this.label = new St.Label({y_align: Clutter.ActorAlign.CENTER, text:_("Mini")});
'''
replacing
'''
this.label.set_style('padding-top: 4px;');
''''
Thanks for your awesome extension!! Great work

**Comment by amivaleo** [comment]
I replaced the label with a symbolic icon: 
![schermata da 2019-02-24 18-56-29](https://user-images.githubusercontent.com/24316547/53303039-f5e83900-3865-11e9-9852-a97970961872.png)

I like to have only icons on the left of the topbar.
If you like it @iamlemec, I copy&paste here what I changed in extension.js, :
```
        Main.wm.addKeybinding('toggle-miniview', this._settings, Meta.KeyBindingFlags.NONE, Shell.ActionMode.NORMAL, Lang.bind(this, this._onToggled));

        this.parent(St.Align.START);
        let box = new St.BoxLayout();
        let icon = new St.Icon({ icon_name: 'emblem-photos-symbolic', style_class: 'system-status-icon emotes-icon'});

        box.add(icon);
        box.add(PopupMenu.arrowIcon(St.Side.BOTTOM));
        this.actor.add_child(box);
        
        // on/off toggle
```

**Comment by iamlemec** [comment]
Oh damn, that is nice. I think it looks best sans arrow icon, as pictured?

I'll merge this in. Thanks!!

**Comment by amivaleo** [comment]
That's my theme: I dislike those arrows, so I edited Adwaita's stylesheet.
I didn't check if it appears or not on another theme.
I suggest you to keep that, for consistency. 🤷‍♂️

**Comment by iamlemec** [comment]
Ah, yeah seems like that's the standard. Adding the arrow back in.

**Comment by amivaleo** [comment]
It took me some time to fix paddings, margins, etc.
But now, it's perfect: 
![schermata da 2019-02-24 20-08-03](https://user-images.githubusercontent.com/24316547/53303876-ea017480-386f-11e9-8fb5-5d17c842a3db.png)

😊
