### ISSUE TITLE
Hard to use using the touchpad

### ISSUE THREAD

**Issue by amivaleo** [iamlemec/miniview#6]
Hi!
I really appreciate your extension, but I can't use it using only my touchpad. In particular: I can't resize the tiny thumbnail-window.
Can you include some alternative way for doing that? Like, for example, holding ctrl down + left click for resizing (just an idea)?

Thank you! :)

**Comment by iamlemec** [comment]
Indeed! Ctrl+left drag resizing is currently implemented here in the github code, and in fact I submitted a new version to gnome extensions a few days ago. It takes some time for them to review things, but I would guess it'll be live there in a few days more.

**Comment by amivaleo** [comment]
Ops.
Ok!
You already fixed this, even before it became a bug! 😄
