### ISSUE TITLE
Feature request: Change keyboard shortcut

### ISSUE THREAD

**Issue by jacobSND** [iamlemec/miniview#9]
It would be nice to be able to remap the keyboard shortcut used to toggle.

**Comment by iamlemec** [comment]
Yup. At some point I'm going to have to make a settings dialog. Hopefully soon!

**Comment by iamlemec** [comment]
Took a while, but there's a settings dialog in the latest release! Now you can set the toggle shortcut to whatever warms your heart.

**Comment by jacobSND** [comment]
Awesome! Thanks for all the hard work. The update does appear to be broken for me, Ubuntu 18.04, but I was able to manually install from a previous version.
